### ISSUE TITLE
Error converting Shadowlands files.

### ISSUE THREAD

**Issue by Dranos-Nupper** [MaxtorCoder/MultiConverter#10]
![9e36e8df47e8d83be89cb03236060804](https://user-images.githubusercontent.com/6026902/102718885-97b20300-42e2-11eb-8228-329ddef031b5.png)

**Comment by MaxtorCoder** [comment]
C'mon man, provide more info. I am not telepathic..

**Comment by Dranos-Nupper** [comment]
the Freshly compiled Version dose seem to converts from models in 9.0.2 Shadowlands
![3c89775813a925146afd78b6c5da8fd6](https://user-images.githubusercontent.com/6026902/102719347-76064b00-42e5-11eb-9c5b-c7a4df1193b3.png)

After clicking FIx. That message pop's up.
i tested if it works in Wrath but the game crashed even after error.

**Comment by MaxtorCoder** [comment]
Probably related to anims. But unfortunately I don't bother with it anymore.

**Comment by Dranos-Nupper** [comment]
it converted successfully with just .skins and .m2  but not sure how to convert .anim

**Comment by MaxtorCoder** [comment]
> it converted successfully with just .skins and .m2  but not sure how to convert .anim

Check wowdev.wiki, you can do it manually.
