### ISSUE TITLE
Errro Log

### ISSUE THREAD

**Issue by Dokman** [MaxtorCoder/MultiConverter#4]
I am converting legion but i am having this error

> Error fixing: e:\legion_extracted\world\arttest\shader\shadertest_01.m2
> Sequence contains no elements
>    at System.Linq.ThrowHelper.ThrowNoElementsException()
>    at MultiConverter.Lib.Converters.M2Converter.FixTXID() in G:\Repos\MultiConverter\MultiConverter.Lib\Converters\ModelConverter.cs:line 236
>    at MultiConverter.Lib.Converters.M2Converter.Fix() in G:\Repos\MultiConverter\MultiConverter.Lib\Converters\ModelConverter.cs:line 138
>    at MultiConverter.GUI.ConverterForm.<>c__DisplayClass8_0.<FixList>b__0(Object sender, DoWorkEventArgs e) in G:\Repos\MultiConverter\MultiConverter.GUI\Form1.cs:line 145
>

**Comment by MaxtorCoder** [comment]
Can you test this model if you extract it from BFA?

**Comment by Dokman** [comment]
okay

**Comment by Dokman** [comment]
it works but in legion not XD @MaxtorCoder

**Comment by MaxtorCoder** [comment]
Yep I know 😂 Have to implement backwards compatibility.

**Comment by Dokman** [comment]
okay i will try to find in the old code how it works and try to implement it.

**Comment by MaxtorCoder** [comment]
No need, thanks.
