### ISSUE TITLE
cata Kalimdor map retroport.

### ISSUE THREAD

**Issue by Shadowynnie** [MaxtorCoder/MultiConverter#8]
Hi Maxtor, I tried to convert cata Kalimdor to LK on my own but I have a problem. (I wanted to modd the continent) Can you please tell me how to convert these 2 adts to LK?? If the Multiconverter is still in development, maybe it can be improved. I added multiconverter 3.3.0 error log, error message screenshot from your latest converter here from Github and even the 2 cata ADTs that could not be converted.

PS: I cannot use the 2 adts from MoP Kalimdor for conversion cuz the noggit will not load the adts. Also there is a post on MC.net with cata/mop maps for 3.3.5 but the 2 ADTs were not converted there - he left them in cata working format...
![unknown](https://user-images.githubusercontent.com/59115799/93005344-78237580-f550-11ea-99e5-fdf0f3ea821f.png)
[Error ADTs and error log.zip](https://github.com/MaxtorCoder/MultiConverter/files/5213283/Error.ADTs.and.error.log.zip)

Best regards
Shadowynnie

**Comment by MaxtorCoder** [comment]
ADTs are not implemented.

**Comment by Shadowynnie** [comment]
You mean that the converter does not convert adts?

**Comment by MaxtorCoder** [comment]
> You mean that the converter does not convert adts?

Not from newer expansions, no. And honestly stopped working on this, sorry.
